# docker-compose.yml
services:
  api:
    build: .
    ports:
      - "80:27017"
    # Прокидываем .env внутрь контейнера
    env_file:
      - .env
    # Говорим Compose взять эти переменные из env_file
    environment:
      - DatabaseSettings__ConnectionString
      - DatabaseSettings__DatabaseName
      - DatabaseSettings__BooksCollectionName
