name: Deploy to Koyeb
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

      - name: Build and deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
            app-name: bookstore-api
            service-name: bookstore-api
            git-builder: docker
            git-docker-dockerfile: Dockerfile
        
            service-ports: "80:http"
            service-checks: |
              http GET /health 5 3
        
            # Environment variables (comma-separated)
            service-env: ASPNETCORE_ENVIRONMENT=Production,MONGODB_CONNECTION=${{ secrets.MONGODB_CONNECTION }}
        
            # Use free tier instance (or eco-nano)
            service-instance-type: free
            service-routes: "/:80"
